services:
  crdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257"  # SQL port
      - "8080:8080"    # Admin UI
    volumes:
      - ./docker/tmp/cockroach/:/cockroach/cockroach-data
      - ./docker/init/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      - COCKROACH_DATABASES=user_db  # Comma-separated list of DB names

networks:
  default:
    name: crdb-network