services:
  cockroachdb:
    build:
      context: .
      dockerfile: docker/init/Dockerfile
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./docker/tmp/cockroach-data:/cockroach/cockroach-data
      - ./docker/init/db.sh:/init-db.sh
    environment:
      - COCKROACH_DBS=user_db,test_db
    networks:
      - cockroach-net

networks:
  cockroach-net:
    driver: bridge